// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFmz3iSNp5YH_rrdq_YZUQkQw_h5a1iCY',
    appId: '1:866289640315:android:6f44e175ab24f527aa93de',
    messagingSenderId: '866289640315',
    projectId: 'yeetfit-43038',
    storageBucket: 'yeetfit-43038.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5-x-XdpPz3Rrr6lfVPaQ1yMiTmAnYOHU',
    appId: '1:866289640315:web:746b7d429b4e694caa93de',
    messagingSenderId: '866289640315',
    projectId: 'yeetfit-43038',
    authDomain: 'yeetfit-43038.firebaseapp.com',
    storageBucket: 'yeetfit-43038.firebasestorage.app',
    measurementId: 'G-F4BTJMP0VF',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUYvzzAx9QwrwLoJ8m8gO0KsZNj4326hY',
    appId: '1:866289640315:ios:b82b8160319f926caa93de',
    messagingSenderId: '866289640315',
    projectId: 'yeetfit-43038',
    storageBucket: 'yeetfit-43038.firebasestorage.app',
    androidClientId: '866289640315-48h6gakdlrf7r0iuu14t2fhp8vcivh11.apps.googleusercontent.com',
    iosClientId: '866289640315-a14l69bmfrn3p4rbtkdr02q1n1dmeohi.apps.googleusercontent.com',
    iosBundleId: 'com.example.yeetfitAdmin',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUYvzzAx9QwrwLoJ8m8gO0KsZNj4326hY',
    appId: '1:866289640315:ios:b82b8160319f926caa93de',
    messagingSenderId: '866289640315',
    projectId: 'yeetfit-43038',
    storageBucket: 'yeetfit-43038.firebasestorage.app',
    androidClientId: '866289640315-48h6gakdlrf7r0iuu14t2fhp8vcivh11.apps.googleusercontent.com',
    iosClientId: '866289640315-a14l69bmfrn3p4rbtkdr02q1n1dmeohi.apps.googleusercontent.com',
    iosBundleId: 'com.example.yeetfitAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5-x-XdpPz3Rrr6lfVPaQ1yMiTmAnYOHU',
    appId: '1:866289640315:web:528033f3b4b1ec4faa93de',
    messagingSenderId: '866289640315',
    projectId: 'yeetfit-43038',
    authDomain: 'yeetfit-43038.firebaseapp.com',
    storageBucket: 'yeetfit-43038.firebasestorage.app',
    measurementId: 'G-HWQHRB9WHE',
  );

}